export interface Project {
  slug: string;
  name: string;
  tagline: string;
  period: string;
  metric?: { value: string; label: string };
  stack: string[];
  summary: string[];
  highlights: string[];
  links: { github?: string; live?: string; download?: string };
  featured: boolean;
}

export const projects: Project[] = [
  {
    slug: "jobflow-ai",
    name: "JobFlow AI",
    tagline:
      "An automation pipeline that finds jobs, scores them against my real resume, tailors an application, and fills out the form itself.",
    period: "2026",
    metric: { value: "6", label: "hour discovery cycle, fully unattended" },
    stack: [
      "n8n",
      "Supabase",
      "OpenAI Batch API",
      "Claude",
      "Playwright",
      "Flask",
      "Docker Compose",
    ],
    summary: [
      "A job search runs on its own schedule: scrape new postings, filter out the ones that were never going to work out, score the rest against my actual background, then tailor a resume and cover letter and submit the application through a real browser.",
      "Built this after getting tired of the manual version of the same loop, and it is the system that now runs my own job search end to end.",
    ],
    highlights: [
      "Two discovery sources (Bright Data and Apify's LinkedIn scraper) run on offset schedules every 6 hours, feeding a shared Supabase table so both write to the same pipeline without colliding.",
      "Deterministic filters run before any AI cost is spent: regex-based detection for hard German-language requirements and 3+ years experience asks, mined and tuned against roughly 1,000 real scraped descriptions to cut false positives, plus company blacklisting and cross-run duplicate detection since the same role often gets reposted under a new listing ID.",
      "Surviving jobs get scored through OpenAI's Batch API against a weighted rubric: role match, tech stack overlap, seniority fit, location, with explicit deductions for red flags like generic staffing agencies or hard German requirements. Batch scoring keeps the cost sane at this volume.",
      "Jobs that clear the bar get a tailored resume and cover letter generated by Claude, rendered to PDF by a small Flask and reportlab service, and hand off to a Playwright service that opens the real application page, maps visible form fields by their label text, uploads the documents, and submits.",
      "The auto-apply step never touches a CAPTCHA. Postings with reCAPTCHA or hCaptcha are detected before any fill attempt and staged for manual submission instead, same as postings where no fillable form can be found.",
      "Runs as a Docker Compose stack (n8n, Postgres, the PDF renderer, the apply service) with every pipeline stage, job, and application outcome tracked in Supabase so a stuck or failed run is visible, not silent.",
    ],
    links: {},
    featured: true,
  },
  {
    slug: "jobmate",
    name: "JobMate",
    tagline:
      "A job marketplace that ranks listings against your actual resume instead of matching keywords in a title.",
    period: "Sep 2024 – Mar 2025",
    metric: { value: "1,000", label: "users, zero paid marketing" },
    stack: [
      "Flask",
      "React",
      "PostgreSQL",
      "Sentence-Transformers",
      "Selenium",
      "LoRA / PEFT",
      "LIME / SHAP",
    ],
    summary: [
      "Full-stack job marketplace that pulls listings from LinkedIn, Indeed, Glassdoor, and Stepstone and turns them into one ranked feed per user, instead of four separate ones to check by hand.",
      "Grew to 1,000 users through word of mouth alone.",
    ],
    highlights: [
      "Scraped 20,000+ listings from four job boards through REST APIs, deduplicated and normalized them into PostgreSQL, then built the ranked, personalized feed on top.",
      "Built a two-stage ranking system: dense retrieval with Sentence-Transformers narrows the candidate pool, then a cross-encoder reranks results against each user's resume. Landed around 95% top-1 accuracy on a held-out evaluation set.",
      "Ran offline A/B experiments comparing BM25, dense retrieval, and cross-encoder reranking using NDCG@10 and MRR. Cross-encoder reranking beat the semantic-only baseline by roughly 18% on NDCG@10.",
      "Fine-tuned an LLM with LoRA and PEFT to generate interview prep content, cutting filler-word rate by about 35% and grammar-error flags by about 25% on an internal evaluation set.",
      "Added LIME and SHAP explainability so a user can see which parts of their resume actually drove a match, not just a bare percentage score.",
      "Moved LLM inference into an async background job with a polling callback so the main API stopped blocking on it. Response times dropped from 10-12 seconds to under 400 milliseconds.",
    ],
    links: { github: "https://github.com/VishalVarwani/Jobscan" },
    featured: true,
  },
  {
    slug: "invoice-to-pay",
    name: "Invoice-to-Pay Agent",
    tagline:
      "An accounts-payable agent that checks an invoice against the purchase order and refuses to touch the ERP without a human's sign-off.",
    period: "Jan 2026 – Apr 2026",
    stack: [
      "FastAPI",
      "LangGraph",
      "Pydantic",
      "LiteParse",
      "Docling",
      "Supabase",
      "n8n",
      "Streamlit",
    ],
    summary: [
      "Open-source prototype for accounts-payable automation, built as a deterministic control graph that takes an invoice from upload through validation, matching, fraud checks, and ERP posting.",
      "Every write to the ERP waits on an explicit human approval, by design.",
    ],
    highlights: [
      "Built the full approval flow as a deterministic LangGraph state machine: schema validation, duplicate detection, 2-way and 3-way PO matching, fraud controls, GL coding, then ERP posting.",
      "Added a hard interrupt in the graph before any ERP write, so the agent stops and waits for explicit human approval instead of assuming its own extraction was correct.",
      "Routed documents through two different parsers depending on structure: LiteParse for clean, structured invoices, Docling for the messy ones with complex layouts.",
      "Replaced in-memory checkpointing with Supabase so workflow state and audit logs survive a restart.",
      "Wired submission triggers and approval notifications through n8n webhooks talking to the FastAPI service.",
      "Locked invoices, POs, delivery notes, and audit records behind strict Pydantic schemas, with pytest coverage across the graph, the services, the API layer, and the parser contracts.",
    ],
    links: { github: "https://github.com/VishalVarwani/invoice-to-pay" },
    featured: true,
  },
  {
    slug: "supply-chain-monitoring",
    name: "Supply Chain Monitoring Agent",
    tagline:
      "Multi-agent system that watches procurement events in real time and decides, on its own, what actually deserves a human's attention.",
    period: "Mar 2026 – May 2026",
    stack: ["LangGraph", "FastAPI", "PostgreSQL", "Redis", "Groq", "DeepEval", "Docker Compose"],
    summary: [
      "Internally named ProcureWatch AI. Three agents split the work of monitoring procurement operations: ingesting events, validating them against policy, and routing anomalies to the right person.",
      "A rule engine handles most cases for free before any LLM gets involved.",
    ],
    highlights: [
      "Split the pipeline across three agents: one ingests inventory and order events from supplier APIs, one runs rule-based and LLM checks against procurement policy through structured tool calls, one routes anomalies by severity and event type.",
      "Rule-based checks handle about 70% of cases at zero LLM cost. The rest go through a two-model split: a 70B model for deep multi-step analysis, a 17B model for classification in under 100ms.",
      "Built an evaluation set of 300+ labeled supply chain events and tested against behavioral criteria, like whether severity was assessed correctly, instead of exact string matching.",
      "Ran three feedback cycles of a preference-based improvement loop, cutting false-positive escalations by about 25%.",
      "Every decision path writes to an immutable audit trail before the pipeline exits. Ships as a Docker Compose stack with a monitoring dashboard.",
    ],
    links: { github: "https://github.com/VishalVarwani/Supply-Chain-Monitoring" },
    featured: true,
  },
  {
    slug: "knowledge-assistant",
    name: "Enterprise Knowledge Assistant",
    tagline: "A RAG system built to say \"I don't know\" rather than make something up.",
    period: "Mar 2026 – May 2026",
    stack: ["LangChain", "Voyage AI", "pgvector", "Supabase", "Streamlit", "DeepEval"],
    summary: [
      "Retrieval-augmented Q&A system for enterprise documents, with hybrid search, strict grounding, and a full evaluation harness rather than a demo that only works on the happy path.",
    ],
    highlights: [
      "Ingests PDFs, Word documents, and web pages through configurable loaders, chunks and embeds them with Voyage AI, and stores everything in pgvector on Supabase.",
      "Combines semantic and keyword search with cross-encoder reranking, improving retrieval precision by about 30% over single-vector search on a 100-query test set.",
      "Grounds every answer in retrieved context with source citations, and runs a five-layer guardrail stack covering prompt injection, PII, off-topic queries, and output faithfulness.",
      "Ran prompt injection tests and boundary probes across 50 adversarial cases and got the unsafe output rate under 1%.",
      "Built an evaluation set of 150+ question-answer pairs and shipped a Streamlit interface with query caching that cut repeat-query latency by about 60%.",
    ],
    links: { github: "https://github.com/VishalVarwani/Enterprise-Knowledge-Assistant" },
    featured: false,
  },
  {
    slug: "document-intelligence",
    name: "AI Document Intelligence Platform",
    tagline:
      "Routes each part of a document to whichever engine is actually cheap enough for that job, instead of sending everything to an LLM.",
    period: "Jan 2026 – Mar 2026",
    stack: ["GCP", "Groq LLaMA 3.3", "Chroma DB", "FastAPI"],
    summary: [
      "End-to-end document processing pipeline on GCP that extracts structure from PDFs, before any retrieval or language model touches them.",
    ],
    highlights: [
      "PDFs arrive through a REST API, land in Cloud Storage, then pass through an extraction pipeline that pulls out headings, paragraphs, tables, captions, and page context.",
      "Classifies each document section and splits the work: structured content goes to a deterministic Python parser, unstructured prose goes to Groq's LLaMA 3.3.",
      "Routing about 60% of content through the cheaper deterministic path cut LLM API costs and trimmed triage time by 30%.",
      "Built a context-aware QA API with multi-step query planning over Chroma DB, improving answer accuracy by about 40% over naive full-document retrieval, with embedding caching for repeated queries.",
    ],
    links: { github: "https://github.com/VishalVarwani/document-retrieval-pipeline" },
    featured: false,
  },
  {
    slug: "clutchtimeai",
    name: "ClutchTimeAI",
    tagline:
      "Interview prep that reads your actual resume and the actual job description, then asks questions that would actually come up.",
    period: "2026",
    stack: ["FastAPI", "LangGraph", "Claude", "ChromaDB", "React", "Docker"],
    summary: [
      "Resume-aware interview prep. Upload a resume and paste a job description, and it generates targeted behavioral, technical, and situational questions grounded in what's actually on the resume, not a generic question bank.",
      "Ships two ways: as a web app, and as a packaged Windows desktop app.",
    ],
    highlights: [
      "Runs a LangGraph pipeline of four typed steps: a resume parser that chunks the PDF into semantic sections, a JD analyzer that extracts role type and seniority signals, a question generator, and an answer evaluator.",
      "Generates 10-15 questions per session across behavioral, technical, and situational categories, tied to the actual job description rather than a template.",
      "Evaluates each answer through RAG retrieval over the parsed resume and returns structured feedback: what was strong, what was missing, what evidence from the resume should have been cited.",
      "The pipeline is stateful across a session, so later questions get harder or more specific based on how earlier ones were answered.",
      "Packaged the same tool as a native Windows desktop app with PyInstaller and pywebview, with a public installer available on GitHub Releases.",
    ],
    links: {
      github: "https://github.com/VishalVarwani/clutchtimeai-release",
    },
    featured: true,
  },
  {
    slug: "ai4finance",
    name: "AI4Finance",
    tagline:
      "Three specialized agents for stock analysis, wrapped in an interface a non-technical investor can actually use.",
    period: "Feb 2025 – Mar 2025",
    stack: ["Streamlit", "BigQuery", "Yahoo Finance API", "NLU routing"],
    summary: [
      "AI-driven financial assistant built solo, combining real-time stock data, news sentiment, and portfolio evaluation behind one Streamlit interface.",
    ],
    highlights: [
      "Built three specialized agents: one aggregating stock news and running sentiment analysis, one answering real-time stock queries against live and historical data, one evaluating portfolio performance through price trends and moving averages.",
      "Processed large financial datasets through BigQuery batch pipelines and cut API response time by about 40% through query optimization.",
      "Used NLU-based routing to send each query to the right agent, instead of one model trying to handle news, chat, and portfolio analysis at once.",
    ],
    links: { github: "https://github.com/VishalVarwani/AI4Finance" },
    featured: false,
  },
  {
    slug: "streaming-pipeline",
    name: "Streaming Data Pipeline for Event Analytics",
    tagline:
      "Kafka to Spark to a lakehouse, load-tested with millions of events to prove that nothing gets dropped.",
    period: "Sep 2024 – Mar 2025",
    stack: ["Kafka", "Spark Structured Streaming", "Delta Lake", "Snowflake", "Kubernetes"],
    summary: [
      "Real-time pipeline for user interaction events, processed through Spark into a three-layer Delta Lake lakehouse and queried through Snowflake for analytics.",
    ],
    highlights: [
      "Built a Kafka ingestion layer processed through Spark Structured Streaming into raw, cleaned, and aggregated Delta Lake tables.",
      "Split storage into those three layers so a change to how one metric gets calculated means reprocessing that aggregation step, not the whole pipeline from scratch.",
      "Ran a load test pushing several million events over a few hours, cross-checking Kafka's topic offsets against every producer's delivery callbacks to confirm zero events lost, not just that the script didn't crash.",
      "Queried the cleaned and aggregated tables through Snowflake for a small analytics dashboard, taking data from a nightly batch refresh to queryable within minutes of an event happening.",
      "Ran the streaming consumers in Kubernetes so they restart automatically on failure instead of needing someone to notice and restart them by hand.",
    ],
    links: {
      github: "https://github.com/VishalVarwani/streaming-event-analytics-pipeline",
    },
    featured: false,
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
export const featuredProjects = projects.filter((p) => p.featured);
